Bump newrelic_rpm from 9.18.0 to 9.19.0 (#988)
Bumps [newrelic_rpm](https://github.com/newrelic/newrelic-ruby-agent)
from 9.18.0 to 9.19.0.
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a
href="https://github.com/newrelic/newrelic-ruby-agent/blob/dev/CHANGELOG.md">newrelic_rpm's
changelog</a>.</em></p>
<blockquote>
<h2>v9.19.0</h2>
<ul>
<li>
<p><strong>Feature: Add Thread ID as attribute to all spans</strong></p>
<p>The agent will now record the Thread ID as an attribute on each span.
<a
href="https://redirect.github.com/newrelic/newrelic-ruby-agent/pull/3122">PR#3122</a></p>
</li>
<li>
<p><strong>Feature: Add support for W3C TraceContext Trace
Flag</strong></p>
<p>Previously, the agent would not use the trace flag field of the
traceparent header for sampling decisions. This could lead to fragmented
traces in the UI. While the default behavior remains unchanged, two new
configuration options,
<code>distributed_tracing.sampler.remote_parent_sampled</code> and
<code>distributed_tracing.sampler.remote_parent_not_sampled</code>, have
been introduced to allow more control over the way sampling decisions
are made. <a
href="https://redirect.github.com/newrelic/newrelic-ruby-agent/pull/3135">PR#3135</a></p>
</li>
<li>
<p><strong>Bugfix: Include request.uri in Transaction events by
default</strong></p>
<p><a
href="https://docs.newrelic.com/attribute-dictionary/?event=Transaction&amp;attribute=request.uri">The
New Relic data dictionary expects Transaction events to have the
<code>request.uri</code> attribute.</a> The Ruby agent now fulfills this
expectation. If you would like to exclude <code>request.uri</code> from
Transaction events, you can do so by setting
<code>transaction_events.attributes.exclude</code> to
<code>'request.uri'</code>. <a
href="https://redirect.github.com/newrelic/newrelic-ruby-agent/pull/3103">PR#3103</a></p>
</li>
<li>
<p><strong>Bugfix: Fix error in Active Job instrumentation when using
perform_all_later</strong></p>
<p>Previously, when Active Job's <code>perform_all_later</code> method
was called and the agent was running, a <code>NoMethodError</code> would
be raised with the message <code>undefined method 'queue_name' for
nil</code>. The error has been fixed and the name of the segment will
reflect the first job in the queue. Our thanks goes to <a
href="https://github.com/tan-linx"><code>@​tan-linx</code></a> for
bringing this to our attention and providing a fix. <a
href="https://redirect.github.com/newrelic/newrelic-ruby-agent/pull/3110">PR#3110</a></p>
</li>
</ul>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/newrelic/newrelic-ruby-agent/commit/ab431d1f998073b21433b21231fed9cadac23fd0"><code>ab431d1</code></a>
Merge pull request <a
href="https://redirect.github.com/newrelic/newrelic-ruby-agent/issues/3161">#3161</a>
from newrelic/use-bot-for-prerelease-pr</li>
<li><a
href="https://github.com/newrelic/newrelic-ruby-agent/commit/ebc627d87db2b1a0e54a903f7c8c09ece6d4d48d"><code>ebc627d</code></a>
Merge pull request <a
href="https://redirect.github.com/newrelic/newrelic-ruby-agent/issues/3162">#3162</a>
from newrelic/changelog-add</li>
<li><a
href="https://github.com/newrelic/newrelic-ruby-agent/commit/165af161b28991967ec09af8fcd01c6e4bc04ef9"><code>165af16</code></a>
Add entry for active job community fix</li>
<li><a
href="https://github.com/newrelic/newrelic-ruby-agent/commit/3e5f908b5372fcc1ece5afb8e026294faec8f08f"><code>3e5f908</code></a>
Use the bot PAT to create prerelease PR</li>
<li><a
href="https://github.com/newrelic/newrelic-ruby-agent/commit/4a45a9e52bc5afdc55ce826b838d057fa6000ce3"><code>4a45a9e</code></a>
Merge pull request <a
href="https://redirect.github.com/newrelic/newrelic-ruby-agent/issues/3158">#3158</a>
from newrelic/prerelease_updates_9.19.0-pre</li>
<li><a
href="https://github.com/newrelic/newrelic-ruby-agent/commit/a5b2f69004dcd317e9d2077da63e579dc22b3269"><code>a5b2f69</code></a>
ci: force</li>
<li><a
href="https://github.com/newrelic/newrelic-ruby-agent/commit/651c18346cc6f9ebc4dd0ef4ace48f3f0071b58c"><code>651c183</code></a>
bump version</li>
<li><a
href="https://github.com/newrelic/newrelic-ruby-agent/commit/ee6ddbea35ad942bae07414c90ef737a8e14432f"><code>ee6ddbe</code></a>
Merge pull request <a
href="https://redirect.github.com/newrelic/newrelic-ruby-agent/issues/3156">#3156</a>
from newrelic/fix-default-error-collector-ignore-mes...</li>
<li><a
href="https://github.com/newrelic/newrelic-ruby-agent/commit/5edd71ede491ad0ad416c12e392b03f6885f02b0"><code>5edd71e</code></a>
Update documented default for ignore_messages</li>
<li><a
href="https://github.com/newrelic/newrelic-ruby-agent/commit/d853c1a58471472c1933b20ca36acf5b939ee324"><code>d853c1a</code></a>
Merge pull request <a
href="https://redirect.github.com/newrelic/newrelic-ruby-agent/issues/3135">#3135</a>
from newrelic/use_w3c_sampled</li>
<li>Additional commits viewable in <a
href="https://github.com/newrelic/newrelic-ruby-agent/compare/9.18.0...9.19.0">compare
view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility
score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=newrelic_rpm&package-manager=bundler&previous-version=9.18.0&new-version=9.19.0)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after
your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating
it. You can achieve the same result by closing it manually
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore this major version` will close this PR and stop
Dependabot creating any more for this major version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop
Dependabot creating any more for this minor version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop
Dependabot creating any more for this dependency (unless you reopen the
PR or upgrade to it yourself)


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>